{
	"class": "patch",
	"id": "oval:com.redhat.rhsa:def:20110027",
	"version": "669",
	"metadata": {
		"title": "RHSA-2011:0027: python security, bug fix, and enhancement update (Low)",
		"affected": {
			"family": "unix",
			"platform": [
				"Red Hat Enterprise Linux 5"
			]
		},
		"reference": [
			{
				"ref_id": "RHSA-2011:0027",
				"ref_url": "https://access.redhat.com/errata/RHSA-2011:0027",
				"source": "RHSA"
			},
			{
				"ref_id": "CVE-2008-5983",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2008-5983",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2009-4134",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2009-4134",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2010-1449",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2010-1449",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2010-1450",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2010-1450",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2010-1634",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2010-1634",
				"source": "CVE"
			},
			{
				"ref_id": "CVE-2010-2089",
				"ref_url": "https://access.redhat.com/security/cve/CVE-2010-2089",
				"source": "CVE"
			}
		],
		"description": "Python is an interpreted, interactive, object-oriented programming\nlanguage.\n\nIt was found that many applications embedding the Python interpreter did\nnot specify a valid full path to the script or application when calling the\nPySys_SetArgv API function, which could result in the addition of the\ncurrent working directory to the module search path (sys.path). A local\nattacker able to trick a victim into running such an application in an\nattacker-controlled directory could use this flaw to execute code with the\nvictim's privileges. This update adds the PySys_SetArgvEx API. Developers\ncan modify their applications to use this new API, which sets sys.argv\nwithout modifying sys.path. (CVE-2008-5983)\n\nMultiple flaws were found in the Python rgbimg module. If an application\nwritten in Python was using the rgbimg module and loaded a\nspecially-crafted SGI image file, it could cause the application to crash\nor, possibly, execute arbitrary code with the privileges of the user\nrunning the application. (CVE-2009-4134, CVE-2010-1449, CVE-2010-1450)\n\nMultiple flaws were found in the Python audioop module. Supplying certain\ninputs could cause the audioop module to crash or, possibly, execute\narbitrary code. (CVE-2010-1634, CVE-2010-2089)\n\nThis update also fixes the following bugs:\n\n* When starting a child process from the subprocess module in Python 2.4,\nthe parent process could leak file descriptors if an error occurred. This\nupdate resolves the issue. (BZ#609017)\n\n* Prior to Python 2.7, programs that used \"ulimit -n\" to enable\ncommunication with large numbers of subprocesses could still monitor only\n1024 file descriptors at a time, which caused an exception:\n\n  ValueError: filedescriptor out of range in select()\n\nThis was due to the subprocess module using the \"select\" system call. The\nmodule now uses the \"poll\" system call, removing this limitation.\n(BZ#609020)\n\n* Prior to Python 2.5, the tarfile module failed to unpack tar files if the\npath was longer than 100 characters. This update backports the tarfile\nmodule from Python 2.5 and the issue no longer occurs. (BZ#263401)\n\n* The email module incorrectly implemented the logic for obtaining\nattachment file names: the get_filename() fallback for using the deprecated\n\"name\" parameter of the \"Content-Type\" header erroneously used the\n\"Content-Disposition\" header. This update backports a fix from Python 2.6,\nwhich resolves this issue. (BZ#644147)\n\n* Prior to version 2.5, Python's optimized memory allocator never released\nmemory back to the system. The memory usage of a long-running Python\nprocess would resemble a \"high-water mark\". This update backports a fix\nfrom Python 2.5a1, which frees unused arenas, and adds a non-standard\nsys._debugmallocstats() function, which prints diagnostic information to\nstderr. Finally, when running under Valgrind, the optimized allocator is\ndeactivated, to allow more convenient debugging of Python memory usage\nissues. (BZ#569093)\n\n* The urllib and urllib2 modules ignored the no_proxy variable, which could\nlead to programs such as \"yum\" erroneously accessing a proxy server for\nURLs covered by a \"no_proxy\" exclusion. This update backports fixes of\nurllib and urllib2, which respect the \"no_proxy\" variable, which fixes\nthese issues. (BZ#549372)\n\nAs well, this update adds the following enhancements:\n\n* This update introduces a new python-libs package, subsuming the majority\nof the content of the core python package. This makes both 32-bit and\n64-bit Python libraries available on PowerPC systems. (BZ#625372)\n\n* The python-libs.i386 package is now available for 64-bit Itanium with the\n32-bit Itanium compatibility mode. (BZ#644761)\n\nAll Python users are advised to upgrade to these updated packages, which\ncontain backported patches to correct these issues and add these\nenhancements.",
		"advisory": {
			"from": "secalert@redhat.com",
			"severity": "Low",
			"rights": "Copyright 2011 Red Hat, Inc.",
			"issued": {
				"date": "2011-01-13"
			},
			"updated": {
				"date": "2011-01-13"
			},
			"cve": [
				{
					"text": "CVE-2008-5983",
					"href": "https://access.redhat.com/security/cve/CVE-2008-5983",
					"impact": "low",
					"public": "20080806",
					"cvss_2": "3.7/AV:L/AC:H/Au:N/C:P/I:P/A:P"
				},
				{
					"text": "CVE-2009-4134",
					"href": "https://access.redhat.com/security/cve/CVE-2009-4134",
					"impact": "low",
					"public": "20100510",
					"cvss_2": "5.1/AV:N/AC:H/Au:N/C:P/I:P/A:P"
				},
				{
					"text": "CVE-2010-1449",
					"href": "https://access.redhat.com/security/cve/CVE-2010-1449",
					"impact": "low",
					"public": "20100510",
					"cvss_2": "5.1/AV:N/AC:H/Au:N/C:P/I:P/A:P"
				},
				{
					"text": "CVE-2010-1450",
					"href": "https://access.redhat.com/security/cve/CVE-2010-1450",
					"impact": "low",
					"public": "20100510",
					"cvss_2": "5.1/AV:N/AC:H/Au:N/C:P/I:P/A:P"
				},
				{
					"text": "CVE-2010-1634",
					"href": "https://access.redhat.com/security/cve/CVE-2010-1634",
					"impact": "low",
					"public": "20100510",
					"cwe": "CWE-190",
					"cvss_2": "5.1/AV:N/AC:H/Au:N/C:P/I:P/A:P"
				},
				{
					"text": "CVE-2010-2089",
					"href": "https://access.redhat.com/security/cve/CVE-2010-2089",
					"impact": "low",
					"public": "20100111",
					"cvss_2": "4.3/AV:N/AC:M/Au:N/C:N/I:N/A:P"
				}
			],
			"bugzilla": [
				{
					"text": "CVE-2008-5983 python: untrusted python modules search path",
					"href": "https://bugzilla.redhat.com/482814",
					"id": "482814"
				},
				{
					"text": "CVE-2009-4134 CVE-2010-1449 CVE-2010-1450 python: rgbimg: multiple security issues",
					"href": "https://bugzilla.redhat.com/541698",
					"id": "541698"
				},
				{
					"text": "CVE-2010-1634 python: audioop: incorrect integer overflow checks",
					"href": "https://bugzilla.redhat.com/590690",
					"id": "590690"
				},
				{
					"text": "CVE-2010-2089 Python: Memory corruption in audioop module",
					"href": "https://bugzilla.redhat.com/598197",
					"id": "598197"
				}
			],
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:redhat:enterprise_linux:5",
					"cpe:/o:redhat:enterprise_linux:5::client",
					"cpe:/o:redhat:enterprise_linux:5::client_workstation",
					"cpe:/o:redhat:enterprise_linux:5::server"
				]
			}
		}
	},
	"criteria": {
		"operator": "OR",
		"criterias": [
			{
				"operator": "AND",
				"criterias": [
					{
						"operator": "OR",
						"criterias": [
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20110027001",
										"comment": "python is earlier than 0:2.4.3-43.el5"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20091176002",
										"comment": "python is signed with Red Hat redhatrelease key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20110027003",
										"comment": "python-devel is earlier than 0:2.4.3-43.el5"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20091176004",
										"comment": "python-devel is signed with Red Hat redhatrelease key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20110027005",
										"comment": "python-libs is earlier than 0:2.4.3-43.el5"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20110027006",
										"comment": "python-libs is signed with Red Hat redhatrelease key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20110027007",
										"comment": "python-tools is earlier than 0:2.4.3-43.el5"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20091176006",
										"comment": "python-tools is signed with Red Hat redhatrelease key"
									}
								]
							},
							{
								"operator": "AND",
								"criterions": [
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20110027009",
										"comment": "tkinter is earlier than 0:2.4.3-43.el5"
									},
									{
										"test_ref": "oval:com.redhat.rhsa:tst:20091176008",
										"comment": "tkinter is signed with Red Hat redhatrelease key"
									}
								]
							}
						]
					}
				],
				"criterions": [
					{
						"test_ref": "oval:com.redhat.rhba:tst:20070331005",
						"comment": "Red Hat Enterprise Linux 5 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:com.redhat.rhba:tst:20070331006",
				"comment": "Red Hat Enterprise Linux must be installed"
			}
		]
	}
}
